# -*- coding: utf-8 -*-
"""Assignment 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apNrMHzv0BJmP1-TjJXTAa1-KGP3eWUM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import datetime

df=pd.read_csv('/content/takehome_users - takehome_users.csv')

df

df['last_session_creation_time']= pd.to_datetime(df['last_session_creation_time'],unit='s')

df

df.describe().T

df['creation_source']=df['creation_source'].map({'PERSONAL_PROJECTS':1,'GUEST_INVITE':2,'ORG_INVITE':3,'SIGNUP':4,'SIGNUP_GOOGLE_AUTH':5})

df

x=df['creation_source'].value_counts()

x

mylabels=['Org invite','Guest Invite','Personal_Projects','Signup','Signup_google_auth']
plt.pie(x,labels=mylabels)
plt.title('Creation Source')
plt.show()

y=df['opted_in_to_mailing_list'].value_counts()

y

mylabels=['Not opted in mailing list','Opted for mailing list']
plt.pie(y,labels=mylabels)
plt.title('Receiving Marketing Mails')
plt.show()

z=df['enabled_for_marketing_drip'].value_counts()

z

mylabels=['Not enabled for marketing drip','Enabled for marketing drip']
plt.pie(z,labels=mylabels)
plt.title('Marketing E-Mail Drip')
plt.show()

a=df['invited_by_user_id'].value_counts()

a.head()

df=pd.read_csv('/content/takehome_user_engagement - takehome_user_engagement.csv')

df

df['date'] = pd.to_datetime(df.time_stamp)

def rolling_count(df_group, frequency):
    return df_group.rolling(frequency, on='date')['user_id'].count()

df['visits_7_days'] = df.groupby('user_id', as_index=False, group_keys=False).apply(rolling_count, '7D')

df[df.visits_7_days >= 3.0]

user_adopted = df.groupby('user_id')['visits_7_days'].max().reset_index()

user_adopted['adopted_user'] = user_adopted['visits_7_days'].apply(lambda x: 1 if x>=3 else 0)

c=user_adopted.adopted_user.value_counts()

c

mylabels=['Not Adopted user','Adopted user']
plt.pie(c,labels=mylabels)
plt.show()

